// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeEat3IDcmysYBjqQ_H3wE_LHUP0Luv6Y',
    appId: '1:555598693883:web:f25ed6385d6e1cfd96775e',
    messagingSenderId: '555598693883',
    projectId: 'project-flutter-59526',
    authDomain: 'project-flutter-59526.firebaseapp.com',
    storageBucket: 'project-flutter-59526.appspot.com',
    measurementId: 'G-092NFV372G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3IO-Vwx0oHbrRUPDg1EPN4YK8PmLvKa8',
    appId: '1:555598693883:android:fbca70894455793996775e',
    messagingSenderId: '555598693883',
    projectId: 'project-flutter-59526',
    storageBucket: 'project-flutter-59526.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCANmFPGNBEOU61dJEzXG-hDenchJYcPEw',
    appId: '1:555598693883:ios:48e78a457efdb50996775e',
    messagingSenderId: '555598693883',
    projectId: 'project-flutter-59526',
    storageBucket: 'project-flutter-59526.appspot.com',
    iosClientId: '555598693883-p40l4jm5v9dlmt006hbd8un3896bdveg.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCANmFPGNBEOU61dJEzXG-hDenchJYcPEw',
    appId: '1:555598693883:ios:94f60395c2dd4ef596775e',
    messagingSenderId: '555598693883',
    projectId: 'project-flutter-59526',
    storageBucket: 'project-flutter-59526.appspot.com',
    iosClientId: '555598693883-pcp3apoua3ambud8g859tet63214bes6.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicflutter.RunnerTests',
  );
}
